x-postgres-variables: &postgres-variables
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_DB: ${POSTGRES_DB}

x-server-variables: &server-variables
  SECRET_KEY: ${SECRET_KEY}
  DEBUG: ${DEBUG}
  ALLOWED_HOSTS: ${ALLOWED_HOSTS}
  DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}


services:
  postgres:
    image: postgres:16.6
    container_name: postgres
    environment: *postgres-variables
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    
  redis:
    image: redis:8.0-M03-alpine
    container_name: redis
    ports:
      - "6377:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    
  server:
    build:
      context: .
    container_name: server
    environment: *server-variables
    ports:
      - "8000:8000"
    depends_on: # it guaranteed that other service will run before this one.
    # to run depended service after it's ready, you should use 'condition: service_healthy'
      postgres:
        condition: service_healthy 
      redis:
        condition: service_healthy